#!/bin/bash

# Create the vpn-dns.sh script
echo "Creating /bin/vpn-dns.sh..."
sudo tee /bin/vpn-dns.sh > /dev/null << 'EOF'
#!/bin/bash

echo "Getting current DNS servers, this takes a couple of seconds"

/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -Command '
$ErrorActionPreference="SilentlyContinue"
Get-NetAdapter -InterfaceDescription "Cisco AnyConnect*" | Get-DnsClientServerAddress | Select -ExpandProperty ServerAddresses
Get-NetAdapter | ?{-not ($_.InterfaceDescription -like "Cisco AnyConnect*") } | Get-DnsClientServerAddress | Select -ExpandProperty ServerAddresses
' | \
    awk 'BEGIN { print "# Generated by vpn fix func on", strftime("%c"); print } { print "nameserver", $1 }' | \
    tr -d '\r' > /etc/resolv.conf

clear
EOF

# Make it executable
echo "Making /bin/vpn-dns.sh executable..."
sudo chmod +x /bin/vpn-dns.sh

# Add sudoers rule
echo "Adding sudoers rule..."
echo "$(whoami) ALL=(ALL) NOPASSWD: /bin/vpn-dns.sh" | sudo tee /etc/sudoers.d/010-$(whoami)-vpn-dns

# Add to profile
echo "Adding script to /etc/profile.d..."
echo "/bin/vpn-dns.sh" | sudo tee /etc/profile.d/vpn-dns.sh

echo "✅ Setup complete!"
